<html>
<head>
<title>TestNG:  Default test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Default test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>11/5/0</td>
</tr><tr>
<td>Started on:</td><td>Fri May 09 17:29:05 CDT 2025</td>
</tr>
<tr><td>Total time:</td><td>155 seconds (155313 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Attribute(s)</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives Success message on submitting valid python code for Find Numbers with Even Number of Digits question", "Arrays PracticeQuestion"</td>
<td><div><pre>java.lang.AssertionError: BUG: Expected message &apos;Submission Successful&apos; but got: &apos;Error occurred during submission&apos; expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
	at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:122)
</pre></div><a href='#' onClick='toggleBox("stack-trace1776486626", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1776486626'><pre>java.lang.AssertionError: BUG: Expected message &apos;Submission Successful&apos; but got: &apos;Error occurred during submission&apos; expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
	at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:122)
</pre></div></td>
<td>9</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives Success message on submitting valid python code for Squares of a Sorted Array question", "Arrays PracticeQuestion"</td>
<td><div><pre>java.lang.AssertionError: BUG: Expected message &apos;Submission Successful&apos; but got: &apos;No tests were collected&apos; expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
	at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:146)
</pre></div><a href='#' onClick='toggleBox("stack-trace2021011079", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2021011079'><pre>java.lang.AssertionError: BUG: Expected message &apos;Submission Successful&apos; but got: &apos;No tests were collected&apos; expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
	at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:146)
</pre></div></td>
<td>9</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives Success message on submitting valid python code for "Search the array" question", "Arrays PracticeQuestion"</td>
<td><div><pre>java.lang.AssertionError: BUG: Expected message &apos;Submission Successful&apos; but got: &apos;Some Tests failed. Please review code&apos; expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
	at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:75)
</pre></div><a href='#' onClick='toggleBox("stack-trace1928075000", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1928075000'><pre>java.lang.AssertionError: BUG: Expected message &apos;Submission Successful&apos; but got: &apos;Some Tests failed. Please review code&apos; expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
	at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:75)
</pre></div></td>
<td>8</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives error on submitting invalid python code for "Max Consecutive Ones" question", "Arrays PracticeQuestion"</td>
<td><div><pre>org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Build info: version: &apos;4.29.0&apos;, revision: &apos;5fc1ec94cb&apos;
System info: os.name: &apos;Windows 11&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;23.0.2&apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [617c117718df0344fcf3885cce333aa4, findElement {value=//input[@value=&apos;Login&apos;], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.93, chrome: {chromedriverVersion: 136.0.7103.92 (cb81a4cc5087..., userDataDir: C:\Users\chand\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50836}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50836/devtoo..., se:cdpVersion: 136.0.7103.93, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 617c117718df0344fcf3885cce333aa4
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
	at stepDefinitions.ArraysStep.the_user_is_in_home_page_after_sign_in(ArraysStep.java:47)
	at ✽.The User is in home page after sign in(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:5)
</pre></div><a href='#' onClick='toggleBox("stack-trace1159348615", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1159348615'><pre>org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Build info: version: &apos;4.29.0&apos;, revision: &apos;5fc1ec94cb&apos;
System info: os.name: &apos;Windows 11&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;23.0.2&apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [617c117718df0344fcf3885cce333aa4, findElement {value=//input[@value=&apos;Login&apos;], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.93, chrome: {chromedriverVersion: 136.0.7103.92 (cb81a4cc5087..., userDataDir: C:\Users\chand\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50836}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50836/devtoo..., se:cdpVersion: 136.0.7103.93, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 617c117718df0344fcf3885cce333aa4
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
	at stepDefinitions.ArraysStep.the_user_is_in_home_page_after_sign_in(ArraysStep.java:47)
	at ✽.The User is in home page after sign in(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:5)
</pre></div></td>
<td>3</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives error on submitting invalid python code for Squares of a Sorted Array question", "Arrays PracticeQuestion"</td>
<td><div><pre>java.lang.AssertionError: BUG: Expected message &apos;Error occurred&apos; but got: &apos;No tests were collected&apos; expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:280)
	at ✽.The user gets error message Error occurred during submission in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:140)
</pre></div><a href='#' onClick='toggleBox("stack-trace278894001", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace278894001'><pre>java.lang.AssertionError: BUG: Expected message &apos;Error occurred&apos; but got: &apos;No tests were collected&apos; expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:280)
	at ✽.The user gets error message Error occurred during submission in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:140)
</pre></div></td>
<td>9</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Attribute(s)</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives error on submitting invalid python code for "Search the array" question", "Arrays PracticeQuestion"</td>
<td></td>
<td>8</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives Success message on submitting valid python code for "Max Consecutive Ones" question", "Arrays PracticeQuestion"</td>
<td></td>
<td>9</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able to run valid python code for Max Consecutive Ones question", "Arrays PracticeQuestion"</td>
<td></td>
<td>10</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives error for invalid python code on running Squares of a Sorted Array question", "Arrays PracticeQuestion"</td>
<td></td>
<td>8</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives error on submitting invalid python code for Find Numbers with Even Number of Digits question", "Arrays PracticeQuestion"</td>
<td></td>
<td>9</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives error for invalid python code on running "Search the array" question", "Arrays PracticeQuestion"</td>
<td></td>
<td>13</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives error for invalid python code on running Search the array question", "Arrays PracticeQuestion"</td>
<td></td>
<td>9</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able to run valid python code for "Search the array" question", "Arrays PracticeQuestion"</td>
<td></td>
<td>8</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user receives error for invalid python code on running Find Numbers with Even Number of Digits question", "Arrays PracticeQuestion"</td>
<td></td>
<td>9</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able to run valid python code for Find Numbers with Even Number of Digits question", "Arrays PracticeQuestion"</td>
<td></td>
<td>8</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
<tr>
<td title='testRunner.DsalgoRunner.runScenario()'><b>runScenario</b><br>Test class: testRunner.DsalgoRunner<br>Test method: Runs Cucumber Scenarios<br>Parameters: "Verify that user is able to run valid python code for Squares of a Sorted Array question", "Arrays PracticeQuestion"</td>
<td></td>
<td>8</td>
<td>testRunner.DsalgoRunner@2525ff7e</td></tr>
</table><p>
</body>
</html>