{"uuid":"43e43548-ac22-48cf-9e0d-ef3a7d22b80b","historyId":"f861f8c1404672ec894e75a2f5d1ad04","fullName":"io.cucumber.testng.AbstractTestNGCucumberTests.runScenario","labels":[{"name":"package","value":"testRunner.DsalgoRunner"},{"name":"testClass","value":"testRunner.DsalgoRunner"},{"name":"testMethod","value":"runScenario"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"testRunner.DsalgoRunner"},{"name":"host","value":"LAPTOP-2KQV9F30"},{"name":"thread","value":"22976@LAPTOP-2KQV9F30.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Runs Cucumber Scenarios","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"BUG: Expected message 'Submission successful' but got: 'Error occurred during submission'","trace":"java.lang.AssertionError: BUG: Expected message 'Submission successful' but got: 'Error occurred during submission'\r\n\tat org.junit.Assert.fail(Assert.java:89)\r\n\tat stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:385)\r\n\tat âœ½.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:129)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg1","value":"\"Arrays PracticeQuestion\""},{"name":"arg0","value":"\"Verify that user receives Success message on submitting valid python code for Find Numbers with Even Number of Digits question\""}],"start":1746290289224,"stop":1746290295417}